replicaCount: 1

image:
  repository: ghcr.io/sidebase/docs/sidebase-docs
  tag: main
  pullPolicy: IfNotPresent

imageCredentials:
  password:

volumes: []

volumeMounts: []

commitShortSHA: 123456

service:
  type: LoadBalancer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: v2.sidebase.io
  ports:
    http:
      port: 80
  health: /
  env:
    - name: "GREET"
      value: "scaffoldWashere"

podAutoscaler:
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75

oauth2:
  enabled: false

ingress:
  enabled: false
  class: nginx
  certManager:
    enabled: true
    issuer: cloudflare-issuer
  url: main.the-scaffold.k8s.sidestream.tech
  timeoutEnabled: false
  annotations: {}

resources:
  limits:
    cpu: 100m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 500Mi
