name: Auto approve and merge PRs by sideborg

# Trigger the workflow on pull request
on:
  pull_request

jobs:
  automerge:
    name: Auto merge after successful checks
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        uses: pascalgn/automerge-action@v0.15.5
        if: github.actor == 'sideborg'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          MERGE_LABELS: ""
          MERGE_METHOD: squash
