name: Auto approve and merge PRs by sideborg

# Trigger the workflow on pull request
on:
  pull_request

jobs:
  autoapprove:
    name: Auto Approve a PR by sideborg
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v2.0.0
        # Perform the auto approve action only when the PR is raised by sideborg
        if: github.actor == 'sideborg'
        with:
          github-token: ${{ secrets.GH_TOKEN }}
  automerge:
    name: Auto merge after successful checks
    # By default, jobs run in parallel. To run the jobs sequentially, they keywords "needs" is needed.
    # Auto merge action can be done only when the PR is approved, hence this automerge needs autoapprove as a prerequisite
    needs: autoapprove
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        # Custom action for auto merging already available on marketplace
        uses: pascalgn/automerge-action@135f0bdb927d9807b5446f7ca9ecc2c51de03c4a
        # Perform the auto merge action only when the PR is raised by sideborg
        if: github.actor == 'sideborg'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          MERGE_LABELS: ""
          MERGE_METHOD: squash
