name: Auto approve and merge PRs by sidebot

# Trigger the workflow on pull request
on:
  pull_request

jobs:
  autoapprove:
    name: Auto Approve a PR by sidebot
    runs-on: ubuntu-latest # Environment on which the job runs
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'sideborg'
        with:
          github-token: ${{ secrets.GH_TOKEN }}
  automerge:
    name: Auto merge after successful checks
    needs: autoapprove
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        uses: pascalgn/automerge-action@135f0bdb927d9807b5446f7ca9ecc2c51de03c4a
        if: github.actor == 'sidebot'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          MERGE_LABELS: sync
          MERGE_METHOD: squash
