name: Auto approve and merge PRs by sideborg

# Trigger the workflow on pull request
on:
  pull_request

jobs:
  autoapprove:
    runs-on: ubuntu-latest
    if: github.actor == 'sideborg'
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GH_APPROVE_TOKEN }}
  automerge:
    name: Auto merge after successful checks
    needs: autoapprove
    if: github.actor == 'sideborg'
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        uses: pascalgn/automerge-action@135f0bdb927d9807b5446f7ca9ecc2c51de03c4a
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          MERGE_LABELS: ""
          MERGE_METHOD: squash
