name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VER: 22.5

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Use Node.js ${{ env.NODE_VER }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VER }}
          cache: 'pnpm'

      - name: Install
        run: pnpm i

      - name: Lint
        run: pnpm lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Use Node.js ${{ env.NODE_VER }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VER }}
          cache: 'pnpm'

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm build
